(()=>{'use strict';
const $=id=>document.getElementById(id),STORE='little_alchemist_v1',MODES=['chem','life','hard'];
const localDay=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const dayDiff=(a,b)=>{try{const A=a.split('-').map(Number),B=b.split('-').map(Number);return Math.round((Date.UTC(B[0],B[1]-1,B[2])-Date.UTC(A[0],A[1]-1,A[2]))/86400000)}catch(e){return 99}};
const load=()=>{try{const r=JSON.parse(localStorage.getItem(STORE)||'{}');return r&&typeof r==='object'?r:{}}catch(e){return{}}};
const r=load(),S={xp:Number(r.xp)||0,lang:r.lang==='en'?'en':'sk',streak:Math.max(1,Number(r.streak)||1),lastOpen:typeof r.lastOpen==='string'?r.lastOpen:'',claimed:typeof r.claimed==='string'?r.claimed:'',progress:{chem:{},life:{},hard:{}}};
MODES.forEach(m=>{if(r.progress&&r.progress[m]&&typeof r.progress[m]==='object')S.progress[m]=r.progress[m]});
const save=()=>{try{localStorage.setItem(STORE,JSON.stringify(S))}catch(e){}};
const td=localDay();if(!S.lastOpen)S.lastOpen=td;else if(S.lastOpen!==td){S.streak=dayDiff(S.lastOpen,td)===1?S.streak+1:1;S.lastOpen=td}save();
const T={sk:{sub:'Akadémia alchýmie',hero:'Miešaj, objavuj a uč sa. 150 úrovní v troch herných cestách.',done:'HOTOVÉ LEVELY',stars:'HVIEZDY',choose:'Vyber cestu',return:'Návratová odmena',daily:'Denná iskra',dailyText:'Otvor hru každý deň a získaj bonus XP.',claim:'Vyzdvihnúť',claimed:'Vyzdvihnuté',lang:'Jazyk',levels:'50 levelov',goal:'CIEĽ',combine:'Vyber dve látky a spoj ich.',odd:'Nájdi jednu vec, ktorá medzi ostatné nepatrí.',wrong:'Táto kombinácia nefunguje. Skús inú dvojicu.',wrongOdd:'Táto vec do skupiny patrí. Skús inú.',doneLevel:'Level dokončený',map:'Mapa',next:'Ďalší level',perfect:'Bez chyby!',mistakes:'Chyby: ',select:'ťukni pre výber',streak:n=>'Séria '+n+(n===1?' deň':' dní'),mode:{chem:['🧪','Chémia','Reakcie, zmesi a materiály.'],life:['🌿','Pre život','Postreh a logika: čo do skupiny nepatrí?'],hard:['🔥','Majster alchýmie','Viackrokové recepty a náročnejšie kombinácie.']}},en:{sub:'Alchemy Academy',hero:'Mix, discover and learn. 150 levels across three learning paths.',done:'LEVELS DONE',stars:'STARS',choose:'Choose a path',return:'Return reward',daily:'Daily spark',dailyText:'Open the game every day and earn bonus XP.',claim:'Claim',claimed:'Claimed',lang:'Language',levels:'50 levels',goal:'GOAL',combine:'Pick two substances and combine them.',odd:'Find the one item that does not belong.',wrong:'That combination does not work. Try another pair.',wrongOdd:'That item belongs to the group. Try another.',doneLevel:'Level complete',map:'Map',next:'Next level',perfect:'Perfect run!',mistakes:'Mistakes: ',select:'tap to select',streak:n=>'Streak '+n+' day'+(n===1?'':'s'),mode:{chem:['🧪','Chemistry','Reactions, mixtures and materials.'],life:['🌿','Everyday logic','Observation and logic: what does not belong?'],hard:['🔥','Master Alchemist','Multi-step recipes and harder combinations.']}}};
const I={h:['⚪','vodík','hydrogen'],o:['🔵','kyslík','oxygen'],water:['💧','voda','water'],na:['🟣','sodík','sodium'],cl:['🟢','chlór','chlorine'],salt:['🧂','soľ','salt'],soil:['🟫','hlina','soil'],mud:['🟤','blato','mud'],ca:['⚪','vápnik','calcium'],lime:['⬜','pálené vápno','quicklime'],slaked:['🥛','hasené vápno','slaked lime'],sand:['🏖️','piesok','sand'],mortar:['🏗️','malta','mortar'],ash:['🌫️','popol','ash'],potash:['🤍','potaš','potash'],glassmix:['🧊','sklárska zmes','glass batch'],limestone:['🪨','vápenec','limestone'],glass:['🪟','sklo','glass'],cu:['🟠','meď','copper'],sn:['⚪','cín','tin'],bronze:['🥉','bronz','bronze'],zn:['🔘','zinok','zinc'],brass:['🟡','mosadz','brass'],fe:['⚙️','železo','iron'],carbon:['⚫','uhlík','carbon'],steel:['🔩','oceľ','steel'],sugar:['🍬','cukor','sugar'],sweet:['🧋','cukrový roztok','sugar solution'],brine:['🌊','slaný roztok','salt solution'],co2:['☁️','oxid uhličitý','carbon dioxide'],sparkling:['🥤','sýtená voda','carbonated water'],vinegar:['🍶','ocot','vinegar'],baking:['🥄','jedlá sóda','baking soda'],foam:['🫧','penivá zmes','fizzy mixture'],oil:['🫗','olej','oil'],emulsion:['🥣','emulzia','emulsion'],straw:['🌾','slama','straw'],adobe:['🧱','nepálená tehla','adobe'],cement:['🏭','cement','cement'],wetcement:['🪣','cementová kaša','cement paste'],concrete:['🧱','betón','concrete'],orefe:['🪨','železná ruda','iron ore'],orecu:['🪨','medená ruda','copper ore']};
const R={},add=(a,b,c)=>R[[a,b].sort().join('+')]=c;[['h','o','water'],['na','cl','salt'],['soil','water','mud'],['ca','o','lime'],['lime','water','slaked'],['slaked','sand','mortar'],['ash','ash','potash'],['sand','potash','glassmix'],['glassmix','limestone','glass'],['cu','sn','bronze'],['cu','zn','brass'],['fe','carbon','steel'],['sugar','water','sweet'],['salt','water','brine'],['co2','water','sparkling'],['vinegar','baking','foam'],['oil','water','emulsion'],['mud','straw','adobe'],['cement','water','wetcement'],['wetcement','sand','concrete'],['orefe','carbon','fe'],['orecu','carbon','cu']].forEach(x=>add(...x));
const BAS=[['h','o','water'],['na','cl','salt'],['soil','water','mud'],['ca','o','lime'],['lime','water','slaked'],['slaked','sand','mortar'],['ash','ash','potash'],['sand','potash','glassmix'],['glassmix','limestone','glass'],['cu','sn','bronze'],['cu','zn','brass'],['fe','carbon','steel'],['sugar','water','sweet'],['salt','water','brine'],['co2','water','sparkling'],['vinegar','baking','foam'],['oil','water','emulsion'],['mud','straw','adobe'],['cement','water','wetcement'],['wetcement','sand','concrete']],DIS=['soil','ash','sand','water','carbon','limestone','sugar','oil','cement','cu','zn','sn'],HARD=[['slaked',['ca','o','water']],['mortar',['ca','o','water','sand']],['glass',['sand','ash','ash','limestone']],['sparkling',['h','o','co2']],['brine',['na','cl','water']],['sweet',['h','o','sugar']],['concrete',['cement','water','sand']],['adobe',['soil','water','straw']],['steel',['orefe','carbon','carbon']],['bronze',['orecu','carbon','sn']]];
const CATS={fruit:[['jablko','apple'],['hruška','pear'],['banán','banana'],['marhuľa','apricot'],['slivka','plum']],days:[['pondelok','Monday'],['utorok','Tuesday'],['streda','Wednesday'],['štvrtok','Thursday'],['piatok','Friday']],vehicles:[['auto','car'],['vlak','train'],['bicykel','bicycle'],['autobus','bus'],['lietadlo','plane']],drinks:[['voda','water'],['čaj','tea'],['džús','juice'],['mlieko','milk'],['limonáda','lemonade']],animals:[['mačka','cat'],['pes','dog'],['koza','goat'],['kôň','horse'],['krava','cow']],tools:[['kladivo','hammer'],['kliešte','pliers'],['skrutkovač','screwdriver'],['píla','saw'],['kľúč','wrench']],shapes:[['kruh','circle'],['štvorec','square'],['trojuholník','triangle'],['obdĺžnik','rectangle'],['ovál','oval']],metals:[['meď','copper'],['železo','iron'],['hliník','aluminium'],['striebro','silver'],['zlato','gold']],clothes:[['tričko','shirt'],['nohavice','trousers'],['čiapka','hat'],['bunda','jacket'],['ponožky','socks']],space:[['Mars','Mars'],['Venuša','Venus'],['Jupiter','Jupiter'],['Saturn','Saturn'],['Merkúr','Mercury']]};
const cats=Object.keys(CATS),shuffle=(a,seed)=>{a=a.slice();let s=seed>>>0,r=()=>((s=(s*1664525+1013904223)>>>0)/4294967296);for(let i=a.length-1;i;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const chem=i=>{let x=BAS[i%BAS.length],a=[x[0],x[1]],n=Math.min(4,Math.floor(i/10));for(let k=0;k<n;k++)a.push(DIS[(i*3+k)%DIS.length]);return{goal:x[2],tiles:shuffle(a,i+11)}};
const hard=i=>{let x=HARD[i%HARD.length],a=x[1].slice();if(i>=20)a.push(DIS[(i+4)%DIS.length]);if(i>=35)a.push(DIS[(i+9)%DIS.length]);return{goal:x[0],tiles:shuffle(a,i+101)}};
const life=i=>{let c=cats[i%cats.length],d=cats[(i+3)%cats.length],base=CATS[c],odd=CATS[d][i%5],pick=[base[i%5],base[(i+1)%5],base[(i+2)%5],odd],order=shuffle([0,1,2,3],i+501);return{items:order.map(x=>pick[x]),odd:order.indexOf(3)}};
const CHEM=Array.from({length:50},(_,i)=>chem(i)),ADV=Array.from({length:50},(_,i)=>hard(i)),LIFE=Array.from({length:50},(_,i)=>life(i));
const stateKey=a=>a.slice().sort().join('|');function solvable(level){const q=[level.tiles.slice()],seen=new Set;while(q.length){const a=q.shift(),k=stateKey(a);if(seen.has(k))continue;seen.add(k);if(a.includes(level.goal))return true;for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){const p=R[[a[i],a[j]].sort().join('+')];if(p){const n=a.slice();n.splice(j,1);n[i]=p;q.push(n)}}if(seen.size>1000)break}return false}
if(CHEM.length!==50||ADV.length!==50||LIFE.length!==50||CHEM.some(x=>!solvable(x))||ADV.some(x=>!solvable(x)))throw new Error('Level validation failed');
let mode='chem',level=0,board=[],sel=null,errors=0,runXp=0,lifeOdd=-1;const tr=()=>T[S.lang],nm=id=>I[id]?(S.lang==='en'?I[id][2]:I[id][1]):id,show=id=>{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('on'));$(id).classList.add('on');window.scrollTo(0,0)},done=()=>MODES.reduce((n,m)=>n+Object.keys(S.progress[m]).length,0),stars=()=>MODES.reduce((n,m)=>n+Object.values(S.progress[m]).reduce((a,b)=>a+(Number(b.stars)||0),0),0),unlock=m=>{let u=1;while(S.progress[m][u]&&u<50)u++;return u};
function home(){const t=tr();$('brandSub').textContent=t.sub;$('heroText').textContent=t.hero;$('doneLbl').textContent=t.done;$('starsLbl').textContent=t.stars;$('chooseTitle').textContent=t.choose;$('returnTitle').textContent=t.return;$('dailyTitle').textContent=t.daily;$('dailyText').textContent=t.dailyText;$('settingsTitle').textContent=t.lang;$('claimBtn').textContent=S.claimed===td?t.claimed:t.claim;$('claimBtn').disabled=S.claimed===td;$('streakLabel').textContent=t.streak(S.streak);$('doneStat').textContent=done()+'/150';$('starsStat').textContent=stars()+'/450';$('xpStat').textContent=S.xp;$('xpTop').textContent=S.xp;$('streakTop').textContent=S.streak;document.documentElement.lang=S.lang;document.querySelectorAll('.langSwitch button').forEach(b=>b.classList.toggle('on',b.dataset.lang===S.lang));const g=$('modeGrid');g.innerHTML='';MODES.forEach(m=>{const a=t.mode[m],d=Object.keys(S.progress[m]).length,b=document.createElement('button');b.className='mode';b.innerHTML='<span class="emoji">'+a[0]+'</span><span><h3>'+a[1]+'</h3><p>'+a[2]+'</p><div class="progress"><i style="width:'+(d*2)+'%"></i></div></span><span class="arrow">›</span>';b.onclick=()=>map(m);g.appendChild(b)})}
function map(m){mode=m;const t=tr(),a=t.mode[m],p=S.progress[m];$('mapTitle').textContent=a[1];$('mapSub').textContent=t.levels;$('mapProg').style.width=(Object.keys(p).length*2)+'%';$('mapStars').innerHTML='<span class="on">★</span> '+Object.values(p).reduce((n,v)=>n+(Number(v.stars)||0),0)+'/150';const max=unlock(m),lm=$('levelMap');lm.innerHTML='';for(let i=1;i<=50;i++){const b=document.createElement('button'),x=p[i];b.className='levelbtn'+(i>max?' lock':'')+(x?' done':'');b.disabled=i>max;b.setAttribute('aria-label','Level '+i+(i>max?' locked':''));b.innerHTML=i+(x?'<span class="mini">'+'★'.repeat(Number(x.stars)||0)+'</span>':'');b.onclick=()=>start(m,i-1);lm.appendChild(b)}show('map')}
function start(m,i){if(i<0||i>49)return;mode=m;level=i;sel=null;errors=0;runXp=0;$('runXp').textContent=0;const t=tr(),a=t.mode[m];$('playTitle').textContent=a[1];$('playSub').textContent='Level '+(i+1)+' / 50';$('goalKicker').textContent=t.goal;$('msg').className='msg';$('msg').textContent=m==='life'?t.odd:t.combine;if(m==='life'){const L=LIFE[i];lifeOdd=L.odd;board=L.items.slice();$('goalText').textContent='🧠 '+(S.lang==='en'?'Odd one out':'Čo sem nepatrí?');$('goalHint').textContent=t.odd;renderLife()}else{const L=(m==='chem'?CHEM:ADV)[i];board=L.tiles.slice();$('goalText').textContent=I[L.goal][0]+' '+nm(L.goal);$('goalHint').textContent=t.combine;renderAlchemy()}show('play')}
function renderAlchemy(){const box=$('tiles');box.innerHTML='';board.forEach((id,i)=>{const b=document.createElement('button');if(!id){b.className='tile empty';b.disabled=true}else{b.className='tile'+(sel===i?' sel':'');b.setAttribute('aria-pressed',sel===i?'true':'false');b.innerHTML='<span class="e">'+I[id][0]+'</span><span class="n">'+nm(id)+'</span><span class="tag">'+tr().select+'</span>';b.onclick=()=>tap(i)}box.appendChild(b)})}
function tap(i){if(!board[i])return;if(sel===null){sel=i;renderAlchemy();return}if(sel===i){sel=null;renderAlchemy();return}const a=board[sel],b=board[i],prod=R[[a,b].sort().join('+')];if(prod){board[sel]=prod;board[i]=null;sel=null;runXp+=4;$('runXp').textContent=runXp;$('msg').className='msg good';$('msg').textContent='✓ '+nm(a)+' + '+nm(b)+' → '+nm(prod);renderAlchemy();const goal=(mode==='chem'?CHEM:ADV)[level].goal;if(prod===goal)setTimeout(win,180)}else{errors++;sel=null;$('msg').className='msg bad';$('msg').textContent=tr().wrong;renderAlchemy()}}
function renderLife(){const box=$('tiles');box.innerHTML='';board.forEach((pair,i)=>{const b=document.createElement('button');b.className='tile';b.innerHTML='<span class="e">❓</span><span class="n">'+pair[S.lang==='en'?1:0]+'</span>';b.onclick=()=>{if(i===lifeOdd){runXp+=6;win()}else{errors++;$('msg').className='msg bad';$('msg').textContent=tr().wrongOdd}};box.appendChild(b)})}
function win(){const st=errors===0?3:errors<=2?2:1,idx=level+1,old=S.progress[mode][idx],oldStars=old?Number(old.stars)||0:0,first=!old,improved=Math.max(0,st-oldStars),earned=(first?15+runXp:0)+improved*5;if(!old||st>oldStars)S.progress[mode][idx]={stars:Math.max(st,oldStars)};S.xp+=earned;save();$('xpTop').textContent=S.xp;$('resultTitle').textContent=tr().doneLevel;$('resultStars').innerHTML=[1,2,3].map(n=>'<span class="'+(n<=st?'on':'')+'">★</span>').join('');$('resultText').textContent=(earned?('+'+earned+' XP · '):'')+(errors===0?tr().perfect:tr().mistakes+errors);$('resultMap').textContent=tr().map;$('resultNext').textContent=tr().next;$('resultNext').disabled=level>=49;show('result')}
$('homeBtn').onclick=()=>{home();show('home')};$('mapBack').onclick=()=>{home();show('home')};$('playBack').onclick=()=>map(mode);$('resultMap').onclick=()=>map(mode);$('resultNext').onclick=()=>level<49&&start(mode,level+1);$('claimBtn').onclick=()=>{if(S.claimed===td)return;S.xp+=20+Math.min(80,S.streak*5);S.claimed=td;save();home()};document.querySelectorAll('.langSwitch button').forEach(b=>b.onclick=()=>{S.lang=b.dataset.lang;save();home()});home();})();